### ISSUE TITLE
Redistribution of code

### ISSUE THREAD

**Issue by Vivero** [finger563/rosmod#2]
Hi, in accordance to the terms of GNU GPL v3, please provide the source of the code for your "UTILITY FUNCTIONS" in your [KRPCI program](https://github.com/finger563/rosmod/blob/master/code/rosmod_v3/tests/testKRPC/krpci/krpci_base.cpp). You may include a link to my source [here](https://github.com/Vivero/KNav/blob/master/KRPCI/src/KRPCI.cpp), state the changes made, and place a copy of my project's [license](https://github.com/Vivero/KNav/blob/master/LICENSE) in your repository.

For reference, you can read about licensing [here](https://tldrlegal.com/license/gnu-general-public-license-v3-%28gpl-3%29), and a discussion about [how to copy code](http://stackoverflow.com/questions/664141/how-do-licenses-such-as-gpl-regard-copying-of-code) licensed under GPL.

I'm happy with you using parts of my code, I only ask that you attribute credit where it is due. 
Thanks!

**Comment by finger563** [comment]
Hey!  Sorry for not putting it in there yet, we hadn't planned on redistributing it yet and hadn't properly segmented things off like we wanted them.  But i'll go ahead and add the license and reference to your code.  (Which is awesome by the way :) )

**Comment by pranav-srinivas-kumar** [comment]
Fixed this issue. Added a link to Vivero's source file and the project's license

https://github.com/finger563/rosmod/commit/88ce4938a78b23fac25f68ade0ff4e0cf6567d1b

**Comment by Vivero** [comment]
Neat, thanks! Good work on this, your implementation with Cheetah is pretty nifty :)
